language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "node"

before_install:
  - npm i -g npm@5.7.1

install:
  - npm i -g webpack
  - npm i

script:
  - npm run build:production
  - npm run lint

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
